/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PSlugIndexRouteImport } from './routes/p.$slug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as PDriveC1RouteImport } from './routes/p.drive.c1'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminQuizRouteImport } from './routes/_authenticated/admin.quiz'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminCasesRouteImport } from './routes/_authenticated/admin.cases'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin.settings.index'
import { Route as AuthenticatedAdminQuizIndexRouteImport } from './routes/_authenticated/admin.quiz.index'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as AuthenticatedAdminPagesIndexRouteImport } from './routes/_authenticated/admin.pages.index'
import { Route as AuthenticatedAdminCasesIndexRouteImport } from './routes/_authenticated/admin.cases.index'
import { Route as PSlugIItemSlugRouteImport } from './routes/p.$slug.i.$itemSlug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as AuthenticatedAdminQuizIdRouteImport } from './routes/_authenticated/admin.quiz.$id'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin.products.$id'
import { Route as AuthenticatedAdminPagesIdRouteImport } from './routes/_authenticated/admin.pages.$id'
import { Route as AuthenticatedAdminCasesIdRouteImport } from './routes/_authenticated/admin.cases.$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasesRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PSlugIndexRoute = PSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const PDriveC1Route = PDriveC1RouteImport.update({
  id: '/p/drive/c1',
  path: '/p/drive/c1',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminQuizRoute = AuthenticatedAdminQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCasesRoute = AuthenticatedAdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminQuizIndexRoute =
  AuthenticatedAdminQuizIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminQuizRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminPagesIndexRoute =
  AuthenticatedAdminPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)
const AuthenticatedAdminCasesIndexRoute =
  AuthenticatedAdminCasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCasesRoute,
  } as any)
const PSlugIItemSlugRoute = PSlugIItemSlugRouteImport.update({
  id: '/p/$slug/i/$itemSlug',
  path: '/p/$slug/i/$itemSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminQuizIdRoute =
  AuthenticatedAdminQuizIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminQuizRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminPagesIdRoute =
  AuthenticatedAdminPagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)
const AuthenticatedAdminCasesIdRoute =
  AuthenticatedAdminCasesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRouteWithChildren
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/process': typeof ProcessRoute
  '/success': typeof SuccessRoute
  '/tools': typeof ToolsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cases/$slug': typeof CasesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/cases': typeof AuthenticatedAdminCasesRouteWithChildren
  '/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/quiz': typeof AuthenticatedAdminQuizRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/p/drive/c1': typeof PDriveC1Route
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/admin/cases/$id': typeof AuthenticatedAdminCasesIdRoute
  '/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/p/$slug/i/$itemSlug': typeof PSlugIItemSlugRoute
  '/admin/cases/': typeof AuthenticatedAdminCasesIndexRoute
  '/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRouteWithChildren
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/process': typeof ProcessRoute
  '/success': typeof SuccessRoute
  '/tools': typeof ToolsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/p/drive/c1': typeof PDriveC1Route
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/p/$slug': typeof PSlugIndexRoute
  '/admin/cases/$id': typeof AuthenticatedAdminCasesIdRoute
  '/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/p/$slug/i/$itemSlug': typeof PSlugIItemSlugRoute
  '/admin/cases': typeof AuthenticatedAdminCasesIndexRoute
  '/admin/pages': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/quiz': typeof AuthenticatedAdminQuizIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRouteWithChildren
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/process': typeof ProcessRoute
  '/success': typeof SuccessRoute
  '/tools': typeof ToolsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cases/$slug': typeof CasesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/_authenticated/admin/cases': typeof AuthenticatedAdminCasesRouteWithChildren
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/quiz': typeof AuthenticatedAdminQuizRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/p/drive/c1': typeof PDriveC1Route
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/_authenticated/admin/cases/$id': typeof AuthenticatedAdminCasesIdRoute
  '/_authenticated/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/p/$slug/i/$itemSlug': typeof PSlugIItemSlugRoute
  '/_authenticated/admin/cases/': typeof AuthenticatedAdminCasesIndexRoute
  '/_authenticated/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/error'
    | '/forgot-password'
    | '/process'
    | '/success'
    | '/tools'
    | '/update-password'
    | '/admin'
    | '/cases/$slug'
    | '/products/$slug'
    | '/admin/cases'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/quiz'
    | '/admin/settings'
    | '/p/drive/c1'
    | '/admin/'
    | '/p/$slug/'
    | '/admin/cases/$id'
    | '/admin/pages/$id'
    | '/admin/products/$id'
    | '/admin/quiz/$id'
    | '/api/public/media/$'
    | '/p/$slug/i/$itemSlug'
    | '/admin/cases/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/quiz/'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/error'
    | '/forgot-password'
    | '/process'
    | '/success'
    | '/tools'
    | '/update-password'
    | '/cases/$slug'
    | '/products/$slug'
    | '/p/drive/c1'
    | '/admin'
    | '/p/$slug'
    | '/admin/cases/$id'
    | '/admin/pages/$id'
    | '/admin/products/$id'
    | '/admin/quiz/$id'
    | '/api/public/media/$'
    | '/p/$slug/i/$itemSlug'
    | '/admin/cases'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/quiz'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/error'
    | '/forgot-password'
    | '/process'
    | '/success'
    | '/tools'
    | '/update-password'
    | '/_authenticated/admin'
    | '/cases/$slug'
    | '/products/$slug'
    | '/_authenticated/admin/cases'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/quiz'
    | '/_authenticated/admin/settings'
    | '/p/drive/c1'
    | '/_authenticated/admin/'
    | '/p/$slug/'
    | '/_authenticated/admin/cases/$id'
    | '/_authenticated/admin/pages/$id'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/quiz/$id'
    | '/api/public/media/$'
    | '/p/$slug/i/$itemSlug'
    | '/_authenticated/admin/cases/'
    | '/_authenticated/admin/pages/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/quiz/'
    | '/_authenticated/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProcessRoute: typeof ProcessRoute
  SuccessRoute: typeof SuccessRoute
  ToolsRoute: typeof ToolsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  PDriveC1Route: typeof PDriveC1Route
  PSlugIndexRoute: typeof PSlugIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  PSlugIItemSlugRoute: typeof PSlugIItemSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof CasesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/$slug/': {
      id: '/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof PSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/p/drive/c1': {
      id: '/p/drive/c1'
      path: '/p/drive/c1'
      fullPath: '/p/drive/c1'
      preLoaderRoute: typeof PDriveC1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz': {
      id: '/_authenticated/admin/quiz'
      path: '/quiz'
      fullPath: '/admin/quiz'
      preLoaderRoute: typeof AuthenticatedAdminQuizRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cases': {
      id: '/_authenticated/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AuthenticatedAdminCasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/quiz/': {
      id: '/_authenticated/admin/quiz/'
      path: '/'
      fullPath: '/admin/quiz/'
      preLoaderRoute: typeof AuthenticatedAdminQuizIndexRouteImport
      parentRoute: typeof AuthenticatedAdminQuizRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/pages/': {
      id: '/_authenticated/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthenticatedAdminPagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
    '/_authenticated/admin/cases/': {
      id: '/_authenticated/admin/cases/'
      path: '/'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AuthenticatedAdminCasesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCasesRoute
    }
    '/p/$slug/i/$itemSlug': {
      id: '/p/$slug/i/$itemSlug'
      path: '/p/$slug/i/$itemSlug'
      fullPath: '/p/$slug/i/$itemSlug'
      preLoaderRoute: typeof PSlugIItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/quiz/$id': {
      id: '/_authenticated/admin/quiz/$id'
      path: '/$id'
      fullPath: '/admin/quiz/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuizIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuizRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/pages/$id': {
      id: '/_authenticated/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AuthenticatedAdminPagesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
    '/_authenticated/admin/cases/$id': {
      id: '/_authenticated/admin/cases/$id'
      path: '/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AuthenticatedAdminCasesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCasesRoute
    }
  }
}

interface AuthenticatedAdminCasesRouteChildren {
  AuthenticatedAdminCasesIdRoute: typeof AuthenticatedAdminCasesIdRoute
  AuthenticatedAdminCasesIndexRoute: typeof AuthenticatedAdminCasesIndexRoute
}

const AuthenticatedAdminCasesRouteChildren: AuthenticatedAdminCasesRouteChildren =
  {
    AuthenticatedAdminCasesIdRoute: AuthenticatedAdminCasesIdRoute,
    AuthenticatedAdminCasesIndexRoute: AuthenticatedAdminCasesIndexRoute,
  }

const AuthenticatedAdminCasesRouteWithChildren =
  AuthenticatedAdminCasesRoute._addFileChildren(
    AuthenticatedAdminCasesRouteChildren,
  )

interface AuthenticatedAdminPagesRouteChildren {
  AuthenticatedAdminPagesIdRoute: typeof AuthenticatedAdminPagesIdRoute
  AuthenticatedAdminPagesIndexRoute: typeof AuthenticatedAdminPagesIndexRoute
}

const AuthenticatedAdminPagesRouteChildren: AuthenticatedAdminPagesRouteChildren =
  {
    AuthenticatedAdminPagesIdRoute: AuthenticatedAdminPagesIdRoute,
    AuthenticatedAdminPagesIndexRoute: AuthenticatedAdminPagesIndexRoute,
  }

const AuthenticatedAdminPagesRouteWithChildren =
  AuthenticatedAdminPagesRoute._addFileChildren(
    AuthenticatedAdminPagesRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminQuizRouteChildren {
  AuthenticatedAdminQuizIdRoute: typeof AuthenticatedAdminQuizIdRoute
  AuthenticatedAdminQuizIndexRoute: typeof AuthenticatedAdminQuizIndexRoute
}

const AuthenticatedAdminQuizRouteChildren: AuthenticatedAdminQuizRouteChildren =
  {
    AuthenticatedAdminQuizIdRoute: AuthenticatedAdminQuizIdRoute,
    AuthenticatedAdminQuizIndexRoute: AuthenticatedAdminQuizIndexRoute,
  }

const AuthenticatedAdminQuizRouteWithChildren =
  AuthenticatedAdminQuizRoute._addFileChildren(
    AuthenticatedAdminQuizRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCasesRoute: typeof AuthenticatedAdminCasesRouteWithChildren
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRouteWithChildren
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminQuizRoute: typeof AuthenticatedAdminQuizRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCasesRoute: AuthenticatedAdminCasesRouteWithChildren,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRouteWithChildren,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRouteWithChildren,
  AuthenticatedAdminQuizRoute: AuthenticatedAdminQuizRouteWithChildren,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CasesRouteChildren {
  CasesSlugRoute: typeof CasesSlugRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesSlugRoute: CasesSlugRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRouteWithChildren,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProcessRoute: ProcessRoute,
  SuccessRoute: SuccessRoute,
  ToolsRoute: ToolsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  PDriveC1Route: PDriveC1Route,
  PSlugIndexRoute: PSlugIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  PSlugIItemSlugRoute: PSlugIItemSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
