/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ToolsSolutionBuilderRouteImport } from './routes/tools.solution-builder'
import { Route as ToolsPhotoWallRouteImport } from './routes/tools.photo-wall'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ToolsSolutionBuilderIndexRouteImport } from './routes/tools.solution-builder.index'
import { Route as ToolsPhotoWallIndexRouteImport } from './routes/tools.photo-wall.index'
import { Route as PSlugIndexRouteImport } from './routes/p.$slug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ToolsSolutionBuilderPcRouteImport } from './routes/tools.solution-builder.pc'
import { Route as ToolsSolutionBuilderNasRouteImport } from './routes/tools.solution-builder.nas'
import { Route as ToolsSolutionBuilderHomeNetworkRouteImport } from './routes/tools.solution-builder.home-network'
import { Route as ToolsSolutionBuilderFullSolutionRouteImport } from './routes/tools.solution-builder.full-solution'
import { Route as PDriveC1RouteImport } from './routes/p.drive.c1'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin.tools'
import { Route as AuthenticatedAdminSolutionBuilderRouteImport } from './routes/_authenticated/admin.solution-builder'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminQuizRouteImport } from './routes/_authenticated/admin.quiz'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminFilesRouteImport } from './routes/_authenticated/admin.files'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminCasesRouteImport } from './routes/_authenticated/admin.cases'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminToolsIndexRouteImport } from './routes/_authenticated/admin.tools.index'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/admin.settings.index'
import { Route as AuthenticatedAdminQuizIndexRouteImport } from './routes/_authenticated/admin.quiz.index'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as AuthenticatedAdminPagesIndexRouteImport } from './routes/_authenticated/admin.pages.index'
import { Route as AuthenticatedAdminExamsIndexRouteImport } from './routes/_authenticated/admin.exams.index'
import { Route as AuthenticatedAdminCasesIndexRouteImport } from './routes/_authenticated/admin.cases.index'
import { Route as AuthenticatedAdminBlogIndexRouteImport } from './routes/_authenticated/admin.blog.index'
import { Route as ToolsSolutionBuilderSTokenRouteImport } from './routes/tools.solution-builder.s.$token'
import { Route as PSlugIItemSlugRouteImport } from './routes/p.$slug.i.$itemSlug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as AuthenticatedAdminQuizIdRouteImport } from './routes/_authenticated/admin.quiz.$id'
import { Route as AuthenticatedAdminProductsIdRouteImport } from './routes/_authenticated/admin.products.$id'
import { Route as AuthenticatedAdminPlatformSettingsRouteImport } from './routes/_authenticated/admin.platform.settings'
import { Route as AuthenticatedAdminPlatformPluginsRouteImport } from './routes/_authenticated/admin.platform.plugins'
import { Route as AuthenticatedAdminPlatformModulesRouteImport } from './routes/_authenticated/admin.platform.modules'
import { Route as AuthenticatedAdminPagesIdRouteImport } from './routes/_authenticated/admin.pages.$id'
import { Route as AuthenticatedAdminExamsIdRouteImport } from './routes/_authenticated/admin.exams.$id'
import { Route as AuthenticatedAdminCasesIdRouteImport } from './routes/_authenticated/admin.cases.$id'
import { Route as AuthenticatedAdminBlogCategoriesRouteImport } from './routes/_authenticated/admin.blog.categories'
import { Route as AuthenticatedAdminBlogIdRouteImport } from './routes/_authenticated/admin.blog.$id'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSolutionBuilderRoute = ToolsSolutionBuilderRouteImport.update({
  id: '/solution-builder',
  path: '/solution-builder',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsPhotoWallRoute = ToolsPhotoWallRouteImport.update({
  id: '/photo-wall',
  path: '/photo-wall',
  getParentRoute: () => ToolsRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ToolsSolutionBuilderIndexRoute =
  ToolsSolutionBuilderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ToolsSolutionBuilderRoute,
  } as any)
const ToolsPhotoWallIndexRoute = ToolsPhotoWallIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToolsPhotoWallRoute,
} as any)
const PSlugIndexRoute = PSlugIndexRouteImport.update({
  id: '/p/$slug/',
  path: '/p/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ToolsSolutionBuilderPcRoute = ToolsSolutionBuilderPcRouteImport.update({
  id: '/pc',
  path: '/pc',
  getParentRoute: () => ToolsSolutionBuilderRoute,
} as any)
const ToolsSolutionBuilderNasRoute = ToolsSolutionBuilderNasRouteImport.update({
  id: '/nas',
  path: '/nas',
  getParentRoute: () => ToolsSolutionBuilderRoute,
} as any)
const ToolsSolutionBuilderHomeNetworkRoute =
  ToolsSolutionBuilderHomeNetworkRouteImport.update({
    id: '/home-network',
    path: '/home-network',
    getParentRoute: () => ToolsSolutionBuilderRoute,
  } as any)
const ToolsSolutionBuilderFullSolutionRoute =
  ToolsSolutionBuilderFullSolutionRouteImport.update({
    id: '/full-solution',
    path: '/full-solution',
    getParentRoute: () => ToolsSolutionBuilderRoute,
  } as any)
const PDriveC1Route = PDriveC1RouteImport.update({
  id: '/p/drive/c1',
  path: '/p/drive/c1',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSolutionBuilderRoute =
  AuthenticatedAdminSolutionBuilderRouteImport.update({
    id: '/solution-builder',
    path: '/solution-builder',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminQuizRoute = AuthenticatedAdminQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFilesRoute = AuthenticatedAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCasesRoute = AuthenticatedAdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminToolsIndexRoute =
  AuthenticatedAdminToolsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminToolsRoute,
  } as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminQuizIndexRoute =
  AuthenticatedAdminQuizIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminQuizRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminPagesIndexRoute =
  AuthenticatedAdminPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)
const AuthenticatedAdminExamsIndexRoute =
  AuthenticatedAdminExamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminCasesIndexRoute =
  AuthenticatedAdminCasesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminCasesRoute,
  } as any)
const AuthenticatedAdminBlogIndexRoute =
  AuthenticatedAdminBlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ToolsSolutionBuilderSTokenRoute =
  ToolsSolutionBuilderSTokenRouteImport.update({
    id: '/s/$token',
    path: '/s/$token',
    getParentRoute: () => ToolsSolutionBuilderRoute,
  } as any)
const PSlugIItemSlugRoute = PSlugIItemSlugRouteImport.update({
  id: '/p/$slug/i/$itemSlug',
  path: '/p/$slug/i/$itemSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminQuizIdRoute =
  AuthenticatedAdminQuizIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminQuizRoute,
  } as any)
const AuthenticatedAdminProductsIdRoute =
  AuthenticatedAdminProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminPlatformSettingsRoute =
  AuthenticatedAdminPlatformSettingsRouteImport.update({
    id: '/platform/settings',
    path: '/platform/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformPluginsRoute =
  AuthenticatedAdminPlatformPluginsRouteImport.update({
    id: '/platform/plugins',
    path: '/platform/plugins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformModulesRoute =
  AuthenticatedAdminPlatformModulesRouteImport.update({
    id: '/platform/modules',
    path: '/platform/modules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesIdRoute =
  AuthenticatedAdminPagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPagesRoute,
  } as any)
const AuthenticatedAdminExamsIdRoute =
  AuthenticatedAdminExamsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedAdminCasesIdRoute =
  AuthenticatedAdminCasesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCasesRoute,
  } as any)
const AuthenticatedAdminBlogCategoriesRoute =
  AuthenticatedAdminBlogCategoriesRouteImport.update({
    id: '/blog/categories',
    path: '/blog/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogIdRoute =
  AuthenticatedAdminBlogIdRouteImport.update({
    id: '/blog/$id',
    path: '/blog/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRouteWithChildren
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/success': typeof SuccessRoute
  '/tools': typeof ToolsRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/tools/photo-wall': typeof ToolsPhotoWallRouteWithChildren
  '/tools/solution-builder': typeof ToolsSolutionBuilderRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/cases': typeof AuthenticatedAdminCasesRouteWithChildren
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/quiz': typeof AuthenticatedAdminQuizRouteWithChildren
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/admin/solution-builder': typeof AuthenticatedAdminSolutionBuilderRoute
  '/admin/tools': typeof AuthenticatedAdminToolsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/p/drive/c1': typeof PDriveC1Route
  '/tools/solution-builder/full-solution': typeof ToolsSolutionBuilderFullSolutionRoute
  '/tools/solution-builder/home-network': typeof ToolsSolutionBuilderHomeNetworkRoute
  '/tools/solution-builder/nas': typeof ToolsSolutionBuilderNasRoute
  '/tools/solution-builder/pc': typeof ToolsSolutionBuilderPcRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/tools/photo-wall/': typeof ToolsPhotoWallIndexRoute
  '/tools/solution-builder/': typeof ToolsSolutionBuilderIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/categories': typeof AuthenticatedAdminBlogCategoriesRoute
  '/admin/cases/$id': typeof AuthenticatedAdminCasesIdRoute
  '/admin/exams/$id': typeof AuthenticatedAdminExamsIdRoute
  '/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/admin/platform/modules': typeof AuthenticatedAdminPlatformModulesRoute
  '/admin/platform/plugins': typeof AuthenticatedAdminPlatformPluginsRoute
  '/admin/platform/settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/p/$slug/i/$itemSlug': typeof PSlugIItemSlugRoute
  '/tools/solution-builder/s/$token': typeof ToolsSolutionBuilderSTokenRoute
  '/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/cases/': typeof AuthenticatedAdminCasesIndexRoute
  '/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
  '/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/tools/': typeof AuthenticatedAdminToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRouteWithChildren
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/success': typeof SuccessRoute
  '/update-password': typeof UpdatePasswordRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/files': typeof AuthenticatedAdminFilesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/solution-builder': typeof AuthenticatedAdminSolutionBuilderRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/p/drive/c1': typeof PDriveC1Route
  '/tools/solution-builder/full-solution': typeof ToolsSolutionBuilderFullSolutionRoute
  '/tools/solution-builder/home-network': typeof ToolsSolutionBuilderHomeNetworkRoute
  '/tools/solution-builder/nas': typeof ToolsSolutionBuilderNasRoute
  '/tools/solution-builder/pc': typeof ToolsSolutionBuilderPcRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/p/$slug': typeof PSlugIndexRoute
  '/tools/photo-wall': typeof ToolsPhotoWallIndexRoute
  '/tools/solution-builder': typeof ToolsSolutionBuilderIndexRoute
  '/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/admin/blog/categories': typeof AuthenticatedAdminBlogCategoriesRoute
  '/admin/cases/$id': typeof AuthenticatedAdminCasesIdRoute
  '/admin/exams/$id': typeof AuthenticatedAdminExamsIdRoute
  '/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/admin/platform/modules': typeof AuthenticatedAdminPlatformModulesRoute
  '/admin/platform/plugins': typeof AuthenticatedAdminPlatformPluginsRoute
  '/admin/platform/settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/p/$slug/i/$itemSlug': typeof PSlugIItemSlugRoute
  '/tools/solution-builder/s/$token': typeof ToolsSolutionBuilderSTokenRoute
  '/admin/blog': typeof AuthenticatedAdminBlogIndexRoute
  '/admin/cases': typeof AuthenticatedAdminCasesIndexRoute
  '/admin/exams': typeof AuthenticatedAdminExamsIndexRoute
  '/admin/pages': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/quiz': typeof AuthenticatedAdminQuizIndexRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/admin/tools': typeof AuthenticatedAdminToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/cases': typeof CasesRouteWithChildren
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/success': typeof SuccessRoute
  '/tools': typeof ToolsRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/tools/photo-wall': typeof ToolsPhotoWallRouteWithChildren
  '/tools/solution-builder': typeof ToolsSolutionBuilderRouteWithChildren
  '/blog/': typeof BlogIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/cases': typeof AuthenticatedAdminCasesRouteWithChildren
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/files': typeof AuthenticatedAdminFilesRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRouteWithChildren
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/quiz': typeof AuthenticatedAdminQuizRouteWithChildren
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/admin/solution-builder': typeof AuthenticatedAdminSolutionBuilderRoute
  '/_authenticated/admin/tools': typeof AuthenticatedAdminToolsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/p/drive/c1': typeof PDriveC1Route
  '/tools/solution-builder/full-solution': typeof ToolsSolutionBuilderFullSolutionRoute
  '/tools/solution-builder/home-network': typeof ToolsSolutionBuilderHomeNetworkRoute
  '/tools/solution-builder/nas': typeof ToolsSolutionBuilderNasRoute
  '/tools/solution-builder/pc': typeof ToolsSolutionBuilderPcRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/p/$slug/': typeof PSlugIndexRoute
  '/tools/photo-wall/': typeof ToolsPhotoWallIndexRoute
  '/tools/solution-builder/': typeof ToolsSolutionBuilderIndexRoute
  '/_authenticated/admin/blog/$id': typeof AuthenticatedAdminBlogIdRoute
  '/_authenticated/admin/blog/categories': typeof AuthenticatedAdminBlogCategoriesRoute
  '/_authenticated/admin/cases/$id': typeof AuthenticatedAdminCasesIdRoute
  '/_authenticated/admin/exams/$id': typeof AuthenticatedAdminExamsIdRoute
  '/_authenticated/admin/pages/$id': typeof AuthenticatedAdminPagesIdRoute
  '/_authenticated/admin/platform/modules': typeof AuthenticatedAdminPlatformModulesRoute
  '/_authenticated/admin/platform/plugins': typeof AuthenticatedAdminPlatformPluginsRoute
  '/_authenticated/admin/platform/settings': typeof AuthenticatedAdminPlatformSettingsRoute
  '/_authenticated/admin/products/$id': typeof AuthenticatedAdminProductsIdRoute
  '/_authenticated/admin/quiz/$id': typeof AuthenticatedAdminQuizIdRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/p/$slug/i/$itemSlug': typeof PSlugIItemSlugRoute
  '/tools/solution-builder/s/$token': typeof ToolsSolutionBuilderSTokenRoute
  '/_authenticated/admin/blog/': typeof AuthenticatedAdminBlogIndexRoute
  '/_authenticated/admin/cases/': typeof AuthenticatedAdminCasesIndexRoute
  '/_authenticated/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
  '/_authenticated/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/quiz/': typeof AuthenticatedAdminQuizIndexRoute
  '/_authenticated/admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/admin/tools/': typeof AuthenticatedAdminToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/error'
    | '/forgot-password'
    | '/process'
    | '/services'
    | '/success'
    | '/tools'
    | '/update-password'
    | '/admin'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/products/$slug'
    | '/tools/photo-wall'
    | '/tools/solution-builder'
    | '/blog/'
    | '/tools/'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/cases'
    | '/admin/exams'
    | '/admin/files'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/quiz'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/solution-builder'
    | '/admin/tools'
    | '/admin/users'
    | '/p/drive/c1'
    | '/tools/solution-builder/full-solution'
    | '/tools/solution-builder/home-network'
    | '/tools/solution-builder/nas'
    | '/tools/solution-builder/pc'
    | '/admin/'
    | '/p/$slug/'
    | '/tools/photo-wall/'
    | '/tools/solution-builder/'
    | '/admin/blog/$id'
    | '/admin/blog/categories'
    | '/admin/cases/$id'
    | '/admin/exams/$id'
    | '/admin/pages/$id'
    | '/admin/platform/modules'
    | '/admin/platform/plugins'
    | '/admin/platform/settings'
    | '/admin/products/$id'
    | '/admin/quiz/$id'
    | '/api/public/media/$'
    | '/p/$slug/i/$itemSlug'
    | '/tools/solution-builder/s/$token'
    | '/admin/blog/'
    | '/admin/cases/'
    | '/admin/exams/'
    | '/admin/pages/'
    | '/admin/products/'
    | '/admin/quiz/'
    | '/admin/settings/'
    | '/admin/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/error'
    | '/forgot-password'
    | '/process'
    | '/services'
    | '/success'
    | '/update-password'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/products/$slug'
    | '/blog'
    | '/tools'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/files'
    | '/admin/logs'
    | '/admin/notifications'
    | '/admin/seo'
    | '/admin/solution-builder'
    | '/admin/users'
    | '/p/drive/c1'
    | '/tools/solution-builder/full-solution'
    | '/tools/solution-builder/home-network'
    | '/tools/solution-builder/nas'
    | '/tools/solution-builder/pc'
    | '/admin'
    | '/p/$slug'
    | '/tools/photo-wall'
    | '/tools/solution-builder'
    | '/admin/blog/$id'
    | '/admin/blog/categories'
    | '/admin/cases/$id'
    | '/admin/exams/$id'
    | '/admin/pages/$id'
    | '/admin/platform/modules'
    | '/admin/platform/plugins'
    | '/admin/platform/settings'
    | '/admin/products/$id'
    | '/admin/quiz/$id'
    | '/api/public/media/$'
    | '/p/$slug/i/$itemSlug'
    | '/tools/solution-builder/s/$token'
    | '/admin/blog'
    | '/admin/cases'
    | '/admin/exams'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/quiz'
    | '/admin/settings'
    | '/admin/tools'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai'
    | '/auth'
    | '/cases'
    | '/contact'
    | '/error'
    | '/forgot-password'
    | '/process'
    | '/services'
    | '/success'
    | '/tools'
    | '/update-password'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/products/$slug'
    | '/tools/photo-wall'
    | '/tools/solution-builder'
    | '/blog/'
    | '/tools/'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/cases'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/files'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/quiz'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/solution-builder'
    | '/_authenticated/admin/tools'
    | '/_authenticated/admin/users'
    | '/p/drive/c1'
    | '/tools/solution-builder/full-solution'
    | '/tools/solution-builder/home-network'
    | '/tools/solution-builder/nas'
    | '/tools/solution-builder/pc'
    | '/_authenticated/admin/'
    | '/p/$slug/'
    | '/tools/photo-wall/'
    | '/tools/solution-builder/'
    | '/_authenticated/admin/blog/$id'
    | '/_authenticated/admin/blog/categories'
    | '/_authenticated/admin/cases/$id'
    | '/_authenticated/admin/exams/$id'
    | '/_authenticated/admin/pages/$id'
    | '/_authenticated/admin/platform/modules'
    | '/_authenticated/admin/platform/plugins'
    | '/_authenticated/admin/platform/settings'
    | '/_authenticated/admin/products/$id'
    | '/_authenticated/admin/quiz/$id'
    | '/api/public/media/$'
    | '/p/$slug/i/$itemSlug'
    | '/tools/solution-builder/s/$token'
    | '/_authenticated/admin/blog/'
    | '/_authenticated/admin/cases/'
    | '/_authenticated/admin/exams/'
    | '/_authenticated/admin/pages/'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/quiz/'
    | '/_authenticated/admin/settings/'
    | '/_authenticated/admin/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  CasesRoute: typeof CasesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  SuccessRoute: typeof SuccessRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PDriveC1Route: typeof PDriveC1Route
  PSlugIndexRoute: typeof PSlugIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  PSlugIItemSlugRoute: typeof PSlugIItemSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/solution-builder': {
      id: '/tools/solution-builder'
      path: '/solution-builder'
      fullPath: '/tools/solution-builder'
      preLoaderRoute: typeof ToolsSolutionBuilderRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/photo-wall': {
      id: '/tools/photo-wall'
      path: '/photo-wall'
      fullPath: '/tools/photo-wall'
      preLoaderRoute: typeof ToolsPhotoWallRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof CasesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/tools/solution-builder/': {
      id: '/tools/solution-builder/'
      path: '/'
      fullPath: '/tools/solution-builder/'
      preLoaderRoute: typeof ToolsSolutionBuilderIndexRouteImport
      parentRoute: typeof ToolsSolutionBuilderRoute
    }
    '/tools/photo-wall/': {
      id: '/tools/photo-wall/'
      path: '/'
      fullPath: '/tools/photo-wall/'
      preLoaderRoute: typeof ToolsPhotoWallIndexRouteImport
      parentRoute: typeof ToolsPhotoWallRoute
    }
    '/p/$slug/': {
      id: '/p/$slug/'
      path: '/p/$slug'
      fullPath: '/p/$slug/'
      preLoaderRoute: typeof PSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/tools/solution-builder/pc': {
      id: '/tools/solution-builder/pc'
      path: '/pc'
      fullPath: '/tools/solution-builder/pc'
      preLoaderRoute: typeof ToolsSolutionBuilderPcRouteImport
      parentRoute: typeof ToolsSolutionBuilderRoute
    }
    '/tools/solution-builder/nas': {
      id: '/tools/solution-builder/nas'
      path: '/nas'
      fullPath: '/tools/solution-builder/nas'
      preLoaderRoute: typeof ToolsSolutionBuilderNasRouteImport
      parentRoute: typeof ToolsSolutionBuilderRoute
    }
    '/tools/solution-builder/home-network': {
      id: '/tools/solution-builder/home-network'
      path: '/home-network'
      fullPath: '/tools/solution-builder/home-network'
      preLoaderRoute: typeof ToolsSolutionBuilderHomeNetworkRouteImport
      parentRoute: typeof ToolsSolutionBuilderRoute
    }
    '/tools/solution-builder/full-solution': {
      id: '/tools/solution-builder/full-solution'
      path: '/full-solution'
      fullPath: '/tools/solution-builder/full-solution'
      preLoaderRoute: typeof ToolsSolutionBuilderFullSolutionRouteImport
      parentRoute: typeof ToolsSolutionBuilderRoute
    }
    '/p/drive/c1': {
      id: '/p/drive/c1'
      path: '/p/drive/c1'
      fullPath: '/p/drive/c1'
      preLoaderRoute: typeof PDriveC1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tools': {
      id: '/_authenticated/admin/tools'
      path: '/tools'
      fullPath: '/admin/tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solution-builder': {
      id: '/_authenticated/admin/solution-builder'
      path: '/solution-builder'
      fullPath: '/admin/solution-builder'
      preLoaderRoute: typeof AuthenticatedAdminSolutionBuilderRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/quiz': {
      id: '/_authenticated/admin/quiz'
      path: '/quiz'
      fullPath: '/admin/quiz'
      preLoaderRoute: typeof AuthenticatedAdminQuizRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/files': {
      id: '/_authenticated/admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AuthenticatedAdminFilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cases': {
      id: '/_authenticated/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AuthenticatedAdminCasesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tools/': {
      id: '/_authenticated/admin/tools/'
      path: '/'
      fullPath: '/admin/tools/'
      preLoaderRoute: typeof AuthenticatedAdminToolsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminToolsRoute
    }
    '/_authenticated/admin/settings/': {
      id: '/_authenticated/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/admin/quiz/': {
      id: '/_authenticated/admin/quiz/'
      path: '/'
      fullPath: '/admin/quiz/'
      preLoaderRoute: typeof AuthenticatedAdminQuizIndexRouteImport
      parentRoute: typeof AuthenticatedAdminQuizRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/pages/': {
      id: '/_authenticated/admin/pages/'
      path: '/'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthenticatedAdminPagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
    '/_authenticated/admin/exams/': {
      id: '/_authenticated/admin/exams/'
      path: '/'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AuthenticatedAdminExamsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/cases/': {
      id: '/_authenticated/admin/cases/'
      path: '/'
      fullPath: '/admin/cases/'
      preLoaderRoute: typeof AuthenticatedAdminCasesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminCasesRoute
    }
    '/_authenticated/admin/blog/': {
      id: '/_authenticated/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AuthenticatedAdminBlogIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/tools/solution-builder/s/$token': {
      id: '/tools/solution-builder/s/$token'
      path: '/s/$token'
      fullPath: '/tools/solution-builder/s/$token'
      preLoaderRoute: typeof ToolsSolutionBuilderSTokenRouteImport
      parentRoute: typeof ToolsSolutionBuilderRoute
    }
    '/p/$slug/i/$itemSlug': {
      id: '/p/$slug/i/$itemSlug'
      path: '/p/$slug/i/$itemSlug'
      fullPath: '/p/$slug/i/$itemSlug'
      preLoaderRoute: typeof PSlugIItemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/quiz/$id': {
      id: '/_authenticated/admin/quiz/$id'
      path: '/$id'
      fullPath: '/admin/quiz/$id'
      preLoaderRoute: typeof AuthenticatedAdminQuizIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuizRoute
    }
    '/_authenticated/admin/products/$id': {
      id: '/_authenticated/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AuthenticatedAdminProductsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/platform/settings': {
      id: '/_authenticated/admin/platform/settings'
      path: '/platform/settings'
      fullPath: '/admin/platform/settings'
      preLoaderRoute: typeof AuthenticatedAdminPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platform/plugins': {
      id: '/_authenticated/admin/platform/plugins'
      path: '/platform/plugins'
      fullPath: '/admin/platform/plugins'
      preLoaderRoute: typeof AuthenticatedAdminPlatformPluginsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platform/modules': {
      id: '/_authenticated/admin/platform/modules'
      path: '/platform/modules'
      fullPath: '/admin/platform/modules'
      preLoaderRoute: typeof AuthenticatedAdminPlatformModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages/$id': {
      id: '/_authenticated/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AuthenticatedAdminPagesIdRouteImport
      parentRoute: typeof AuthenticatedAdminPagesRoute
    }
    '/_authenticated/admin/exams/$id': {
      id: '/_authenticated/admin/exams/$id'
      path: '/$id'
      fullPath: '/admin/exams/$id'
      preLoaderRoute: typeof AuthenticatedAdminExamsIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/admin/cases/$id': {
      id: '/_authenticated/admin/cases/$id'
      path: '/$id'
      fullPath: '/admin/cases/$id'
      preLoaderRoute: typeof AuthenticatedAdminCasesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCasesRoute
    }
    '/_authenticated/admin/blog/categories': {
      id: '/_authenticated/admin/blog/categories'
      path: '/blog/categories'
      fullPath: '/admin/blog/categories'
      preLoaderRoute: typeof AuthenticatedAdminBlogCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog/$id': {
      id: '/_authenticated/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminCasesRouteChildren {
  AuthenticatedAdminCasesIdRoute: typeof AuthenticatedAdminCasesIdRoute
  AuthenticatedAdminCasesIndexRoute: typeof AuthenticatedAdminCasesIndexRoute
}

const AuthenticatedAdminCasesRouteChildren: AuthenticatedAdminCasesRouteChildren =
  {
    AuthenticatedAdminCasesIdRoute: AuthenticatedAdminCasesIdRoute,
    AuthenticatedAdminCasesIndexRoute: AuthenticatedAdminCasesIndexRoute,
  }

const AuthenticatedAdminCasesRouteWithChildren =
  AuthenticatedAdminCasesRoute._addFileChildren(
    AuthenticatedAdminCasesRouteChildren,
  )

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsIdRoute: typeof AuthenticatedAdminExamsIdRoute
  AuthenticatedAdminExamsIndexRoute: typeof AuthenticatedAdminExamsIndexRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsIdRoute: AuthenticatedAdminExamsIdRoute,
    AuthenticatedAdminExamsIndexRoute: AuthenticatedAdminExamsIndexRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedAdminPagesRouteChildren {
  AuthenticatedAdminPagesIdRoute: typeof AuthenticatedAdminPagesIdRoute
  AuthenticatedAdminPagesIndexRoute: typeof AuthenticatedAdminPagesIndexRoute
}

const AuthenticatedAdminPagesRouteChildren: AuthenticatedAdminPagesRouteChildren =
  {
    AuthenticatedAdminPagesIdRoute: AuthenticatedAdminPagesIdRoute,
    AuthenticatedAdminPagesIndexRoute: AuthenticatedAdminPagesIndexRoute,
  }

const AuthenticatedAdminPagesRouteWithChildren =
  AuthenticatedAdminPagesRoute._addFileChildren(
    AuthenticatedAdminPagesRouteChildren,
  )

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsIdRoute: typeof AuthenticatedAdminProductsIdRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsIdRoute: AuthenticatedAdminProductsIdRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminQuizRouteChildren {
  AuthenticatedAdminQuizIdRoute: typeof AuthenticatedAdminQuizIdRoute
  AuthenticatedAdminQuizIndexRoute: typeof AuthenticatedAdminQuizIndexRoute
}

const AuthenticatedAdminQuizRouteChildren: AuthenticatedAdminQuizRouteChildren =
  {
    AuthenticatedAdminQuizIdRoute: AuthenticatedAdminQuizIdRoute,
    AuthenticatedAdminQuizIndexRoute: AuthenticatedAdminQuizIndexRoute,
  }

const AuthenticatedAdminQuizRouteWithChildren =
  AuthenticatedAdminQuizRoute._addFileChildren(
    AuthenticatedAdminQuizRouteChildren,
  )

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminToolsRouteChildren {
  AuthenticatedAdminToolsIndexRoute: typeof AuthenticatedAdminToolsIndexRoute
}

const AuthenticatedAdminToolsRouteChildren: AuthenticatedAdminToolsRouteChildren =
  {
    AuthenticatedAdminToolsIndexRoute: AuthenticatedAdminToolsIndexRoute,
  }

const AuthenticatedAdminToolsRouteWithChildren =
  AuthenticatedAdminToolsRoute._addFileChildren(
    AuthenticatedAdminToolsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCasesRoute: typeof AuthenticatedAdminCasesRouteWithChildren
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminFilesRoute: typeof AuthenticatedAdminFilesRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRouteWithChildren
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminQuizRoute: typeof AuthenticatedAdminQuizRouteWithChildren
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminSolutionBuilderRoute: typeof AuthenticatedAdminSolutionBuilderRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBlogIdRoute: typeof AuthenticatedAdminBlogIdRoute
  AuthenticatedAdminBlogCategoriesRoute: typeof AuthenticatedAdminBlogCategoriesRoute
  AuthenticatedAdminPlatformModulesRoute: typeof AuthenticatedAdminPlatformModulesRoute
  AuthenticatedAdminPlatformPluginsRoute: typeof AuthenticatedAdminPlatformPluginsRoute
  AuthenticatedAdminPlatformSettingsRoute: typeof AuthenticatedAdminPlatformSettingsRoute
  AuthenticatedAdminBlogIndexRoute: typeof AuthenticatedAdminBlogIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCasesRoute: AuthenticatedAdminCasesRouteWithChildren,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
  AuthenticatedAdminFilesRoute: AuthenticatedAdminFilesRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRouteWithChildren,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRouteWithChildren,
  AuthenticatedAdminQuizRoute: AuthenticatedAdminQuizRouteWithChildren,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminSolutionBuilderRoute:
    AuthenticatedAdminSolutionBuilderRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBlogIdRoute: AuthenticatedAdminBlogIdRoute,
  AuthenticatedAdminBlogCategoriesRoute: AuthenticatedAdminBlogCategoriesRoute,
  AuthenticatedAdminPlatformModulesRoute:
    AuthenticatedAdminPlatformModulesRoute,
  AuthenticatedAdminPlatformPluginsRoute:
    AuthenticatedAdminPlatformPluginsRoute,
  AuthenticatedAdminPlatformSettingsRoute:
    AuthenticatedAdminPlatformSettingsRoute,
  AuthenticatedAdminBlogIndexRoute: AuthenticatedAdminBlogIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CasesRouteChildren {
  CasesSlugRoute: typeof CasesSlugRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesSlugRoute: CasesSlugRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface ToolsPhotoWallRouteChildren {
  ToolsPhotoWallIndexRoute: typeof ToolsPhotoWallIndexRoute
}

const ToolsPhotoWallRouteChildren: ToolsPhotoWallRouteChildren = {
  ToolsPhotoWallIndexRoute: ToolsPhotoWallIndexRoute,
}

const ToolsPhotoWallRouteWithChildren = ToolsPhotoWallRoute._addFileChildren(
  ToolsPhotoWallRouteChildren,
)

interface ToolsSolutionBuilderRouteChildren {
  ToolsSolutionBuilderFullSolutionRoute: typeof ToolsSolutionBuilderFullSolutionRoute
  ToolsSolutionBuilderHomeNetworkRoute: typeof ToolsSolutionBuilderHomeNetworkRoute
  ToolsSolutionBuilderNasRoute: typeof ToolsSolutionBuilderNasRoute
  ToolsSolutionBuilderPcRoute: typeof ToolsSolutionBuilderPcRoute
  ToolsSolutionBuilderIndexRoute: typeof ToolsSolutionBuilderIndexRoute
  ToolsSolutionBuilderSTokenRoute: typeof ToolsSolutionBuilderSTokenRoute
}

const ToolsSolutionBuilderRouteChildren: ToolsSolutionBuilderRouteChildren = {
  ToolsSolutionBuilderFullSolutionRoute: ToolsSolutionBuilderFullSolutionRoute,
  ToolsSolutionBuilderHomeNetworkRoute: ToolsSolutionBuilderHomeNetworkRoute,
  ToolsSolutionBuilderNasRoute: ToolsSolutionBuilderNasRoute,
  ToolsSolutionBuilderPcRoute: ToolsSolutionBuilderPcRoute,
  ToolsSolutionBuilderIndexRoute: ToolsSolutionBuilderIndexRoute,
  ToolsSolutionBuilderSTokenRoute: ToolsSolutionBuilderSTokenRoute,
}

const ToolsSolutionBuilderRouteWithChildren =
  ToolsSolutionBuilderRoute._addFileChildren(ToolsSolutionBuilderRouteChildren)

interface ToolsRouteChildren {
  ToolsPhotoWallRoute: typeof ToolsPhotoWallRouteWithChildren
  ToolsSolutionBuilderRoute: typeof ToolsSolutionBuilderRouteWithChildren
  ToolsIndexRoute: typeof ToolsIndexRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsPhotoWallRoute: ToolsPhotoWallRouteWithChildren,
  ToolsSolutionBuilderRoute: ToolsSolutionBuilderRouteWithChildren,
  ToolsIndexRoute: ToolsIndexRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  CasesRoute: CasesRouteWithChildren,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  SuccessRoute: SuccessRoute,
  ToolsRoute: ToolsRouteWithChildren,
  UpdatePasswordRoute: UpdatePasswordRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PDriveC1Route: PDriveC1Route,
  PSlugIndexRoute: PSlugIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  PSlugIItemSlugRoute: PSlugIItemSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
